import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  sidebar: [
    "introduction",
    {
      type: "category",
      label: "The Journey Begins",
      link: {
        type: "generated-index",
        description:
          "One does not simply walk into Unreal Engine, but all great journeys begin with a single step - you just have to take it.",
        slug: "/the-journey-begins",
      },
      items: [{ type: "autogenerated", dirName: "the-journey-begins" }],
    },
    {
      type: "category",
      label: "Miscellaneous",
      link: {
        type: "generated-index",
        description:
          "A collection of miscellaneous guides that I can't decide on a category for :)",
        slug: "/miscellaneous",
      },
      items: [{ type: "autogenerated", dirName: "miscellaneous" }],
    },
    {
      type: "category",
      label: "Reference",
      link: {
        type: "generated-index",
        description:
          "A collection of references and resources to help you on your journey.",
        slug: "/reference",
      },
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
  ],
};
export default sidebars;
